---
all:
  hosts:
    server_11:
      ansible_host: 192.168.213.11
      ansible_user: yun
    server_21:
      ansible_host: 192.168.213.21
      ansible_user: yun
    host104:
      ansible_host: 192.168.213.104
      ansible_user: public
  children:
    servers:
      hosts:
        server1:
          ansible_host: 192.168.213.11
          ansible_user: yun
    kylin_hosts:
      hosts:
        host1:
          ansible_host: 192.168.213.104
          ansible_user: public
    switches:
      hosts:
        switch1:
        switch2:
