---
all:
  hosts:
    server_11:
      ansible_host: 192.168.213.11
      ansible_user: public
  children:
    servers:
      hosts:
        server1:
          ansible_host: 192.168.213.11
          ansible_user: public
    db_servers:
      hosts:
        server3:
          ansible_host: 192.168.1.103
    switches:
      hosts:
        switch1:
        switch2:
